---
- name: create motd
  ansible.builtin.template:
    src: "etc/motd.j2"
    dest: "/etc/motd"
    owner: "root"
    group: "root"
    mode: '0644'
  tags:
    # the sorting of interfaces and mounts
    # is not idempotent
    - molecule-idempotence-notest
