---
- name: create motd
  ansible.builtin.template:
    src: "etc/motd.j2"
    dest: "/etc/motd"
    owner: "root"
    group: "root"
    mode: '0644'

- name: remove /etc/update-motd.d
  ansible.builtin.file:
    path: "/etc/update-motd.d"
    state: absent
  when:
    - motd_remove_dynamic_motd | bool
