---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: "Test if /etc/motd exists"
      ansible.builtin.lineinfile:
        name: '/etc/motd'
        line: '             This system is managed by Ansible'
        state: present
      check_mode: true
      register: molecule_motd
      failed_when: (molecule_motd is changed) or (molecule_motd is failed)
